### ISSUE TITLE
handle group by for aggregate functions

### ISSUE THREAD

**Issue by ghost** [chkal/criteria4jpa#1]
Hi,

Unfortunatly the following is not working : 

```
Criteria c = CriteriaUtils.createCriteria(em, Logger.class); 
c.setProjection(Projections.projectionList() 
    .add(Projections.property("category")) 
    .add(Projections.property("component")) 
    .add(Projections.sum("value")) 
); 
```

jpa equivalant : 

```
Query q = em.createQuery("SELECT l.category,l.component, SUM(l.value) 
FROM Logger l WHERE l.level = 0  GROUP BY l.category,l.component")
```

Could you add this fonctionnality ?

Thanks and Regards

**Comment by chkal** [comment]
Sure! I'll target the for the next release!

**Comment by chkal** [comment]
I just deployed a new snapshot with "GROUP BY" support.

Now you can do something like:

```
Criteria c = CriteriaUtils.createCriteria(em, Logger.class); 
c.setProjection(Projections.projectionList() 
    .add(Projections.sum("value")) 
    .add(Projections.groupProperty("category")) 
); 
```

Could you perhaps try the new "0.3-SNAPSHOT" and tell me if it fits your needs? See the "development snapshots" section here:

http://www.criteria4jpa.org/install.html

Thanks

**Comment by ghost** [comment]
Hello,

I have used the new 0.3-SNAPSHOT and it is working fine !

Great Thanks.

**Comment by chkal** [comment]
Thanks for testing! :)
